import{a as d,S as m,i as n}from"./assets/vendor-Dy2ZTtfi.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const o of t.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&r(o)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function r(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const p="https://pixabay.com/api/",y="50996745-5a4776a4c42baac1baf275d14",g=15;async function h(i,a=1){const s={key:y,q:i,image_type:"photo",orientation:"horizontal",safesearch:!0,page:a,per_page:g},{data:r}=await d.get(p,{params:s});return r}const l=document.querySelector(".gallery"),c=document.querySelector(".loader");document.querySelector(".more-button");const b=new m(".gallery a",{captionsData:"alt",captionDelay:250});function L(i){const a=i.map(({webformatURL:s,largeImageURL:r,tags:e,likes:t,views:o,comments:u,downloads:f})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${r}">
          <img src="${s}" alt="${e}" width="360" height="200" loading="lazy" />
        </a>
        <ul class="info">
          <li class="info-item"><span class="info-label">Likes</span><span class="info-value">${t}</span></li>
          <li class="info-item"><span class="info-label">Views</span><span class="info-value">${o}</span></li>
          <li class="info-item"><span class="info-label">Comments</span><span class="info-value">${u}</span></li>
          <li class="info-item"><span class="info-label">Downloads</span><span class="info-value">${f}</span></li>
        </ul>
      </li>`).join("");l.insertAdjacentHTML("beforeend",a),b.refresh()}function w(){l.innerHTML=""}function v(){c.classList.remove("is-hidden")}function P(){c.classList.add("is-hidden")}document.querySelector(".form").addEventListener("submit",async i=>{i.preventDefault();let a="";const s={title:"",titleColor:"red",position:"topRight"},r=i.target.elements["search-text"].value.trim();if(r!==""){a=r,w(),v();try{const t=(await h(a)).hits;t.length!==0?L(t):(s.title="Sorry, there are no images matching your search query. Please try again!",n.show(s))}catch(e){s.title="An error occurred while fetching images. Please try again later.",n.show(s),console.error("Fetch error:",e)}finally{P()}}else s.title="Form field must be filled in!",n.show(s);i.target.reset()});
//# sourceMappingURL=index.js.map
